apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v3.1.7
resources:
- ./application-controller
- ./repo-server
- ./dex
- ./notification
- ./server
- ./config
- ./redis
- ./applicationset-controller
- ingress/traefik.yaml
