apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization



helmChartInflationGenerator:
  - chartName: homepage
    chartRepoUrl: https://jameswynn.github.io/helm-charts
    chartVersion: 2.0.1
    releaseName: homepage
    values: values.yaml

namespace: homepage

resources:
  - ingress.yaml
  - feed