apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: feed
  namespace: homepage
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Feed
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`feed.rafaelbroseghini.com`)
      services:
        - name: feed
          port: 8000
      middlewares:
      - name: redirectscheme-http