apiVersion: v1
kind: Service
metadata:
  name: feed
  namespace: homepage
spec:
  externalName: 192.168.0.144
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  type: ExternalName