apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rafaelbroseghini
  namespace: cert-manager
spec:
  secretName: rafaelbroseghini-cert
  issuerRef:
    name: letsencrypt
  dnsNames:
  - '*.rafaelbroseghini.com'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,pihole,homepage,authentik"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
